# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('improvements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='improvements',
            name='upvoted',
            field=models.IntegerField(default=0),
        ),
    ]
