# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 09:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bugs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugs',
            name='upvoted',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
