# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0002_bugs_upvoted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bugs',
            name='upvoted',
        ),
        migrations.AddField(
            model_name='bugs',
            name='upvoted',
            field=models.IntegerField(default=0),
        ),
    ]
